<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Data Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h2 {
            margin: 0;
            font-size: 20px;
        }
        .report-meta {
            margin-bottom: 20px;
        }
        .report-meta table {
            width: 100%;
        }
        .employee-table {
            width: 100%;
            border-collapse: collapse;
        }
        .employee-table th, .employee-table td {
            border: 1px solid #ccc;
            padding: 3px 4px;
            text-align: left;
        }
        .employee-table th {
            background-color: #f5f5f5;
        }
        .footer {
            margin-top: 30px;
            font-size: 11px;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Employee Report</h2>
        <p>Generated on: {{ now()->format('d M Y') }}</p>
    </div>

    <div class="report-meta">
        <table>
            <tr>
                <td><strong>Generated By:</strong> {{ $generated_by ?? 'System' }}</td>
                <td><strong>Generated At:</strong> {{ now()->format('d M Y, H:i') }}</td>
            </tr>
        </table>
    </div>

    <table class="employee-table">
        <thead>
            <tr>
                <th>No</th>
                <th>Employee Code</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Position</th>
                <th>Gender</th>
                <th>Join Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($employees as $index => $employee)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $employee->employee_code }}</td>
                    <td>{{ $employee->full_name }}</td>
                    <td>{{ $employee->email }}</td>
                    <td>{{ $employee->phone }}</td>
                    <td>{{ $employee->position->position_name ?? '-' }}</td>
                    <td>{{ ucfirst($employee->gender) }}</td>
                    <td>{{ \Carbon\Carbon::parse($employee->join_date)->format('d M Y') }}</td>
                    <td>{{ ucfirst($employee->status) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align: center;">No employee data available.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Printed on {{ now()->format('d-m-Y H:i') }}
    </div>
</body>
</html>
