<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Salary Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h2 {
            margin: 0;
            font-size: 20px;
        }
        .report-meta {
            margin-bottom: 20px;
        }
        .report-meta table {
            width: 100%;
            font-size: 12px;
        }
        .salary-table {
            width: 100%;
            border-collapse: collapse;
        }
        .salary-table th, .salary-table td {
            border: 1px solid #ccc;
            padding: 6px 8px;
            text-align: left;
        }
        .salary-table th {
            background-color: #f5f5f5;
        }
        .total-section {
            margin-top: 20px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Salary Report</h2>
        <p>Period: {{ $summary['period'] ?? 'N/A' }}</p>
    </div>

    <div class="report-meta">
        <table>
            <tr>
                <td><strong>Generated By:</strong> {{ $generated_by ?? 'System' }}</td>
                <td><strong>Generated At:</strong> {{ now()->format('d M Y, H:i') }}</td>
            </tr>
        </table>
    </div>

    <table class="salary-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Employee</th>
                <th>Base Salary</th>
                <th>Bonus</th>
                <th>Deductions</th>
                <th>Total Paid</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($salaries as $index => $salary)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $salary->employee->full_name ?? '-' }}</td>
                    <td>Rp {{ number_format($salary->salarySetting->default_salary, 0, ',', '.') }}</td>
                    <td>Rp {{ number_format($salary->bonus, 0, ',', '.') }}</td>
                    <td>Rp {{ number_format($salary->deduction, 0, ',', '.') }}</td>
                    <td>Rp {{ number_format($salary->total_salary, 0, ',', '.') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center;">No salary data available.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="total-section">
        <p>Total Salary Paid: Rp {{ number_format($summary['paid'], 0, ',', '.') }}</p>
        <p>Total Bonus: Rp {{ number_format($summary['bonus'], 0, ',', '.') }}</p>
        <p>Total Deduction: Rp {{ number_format($summary['deduction'], 0, ',', '.') }}</p>
    </div>

    <div class="footer">
        Printed in {{ now()->format('d-m-Y H:i') }}
    </div>
</body>
</html>
