<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Time Off Request Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h2 {
            margin: 0;
            font-size: 20px;
        }
        .report-meta {
            margin-bottom: 20px;
        }
        .report-meta table {
            width: 100%;
        }
        .request-table {
            width: 100%;
            border-collapse: collapse;
        }
        .request-table th, .request-table td {
            border: 1px solid #ccc;
            padding: 6px 8px;
            text-align: left;
        }
        .request-table th {
            background-color: #f5f5f5;
        }
        .summary {
            margin-top: 20px;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            font-size: 11px;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Monthly Time Off Request Report</h2>
        <p>Period: {{ $summary['period'] ?? 'N/A' }}</p>
    </div>

    <div class="report-meta">
        <table>
            <tr>
                <td><strong>Generated By:</strong> {{ $generated_by ?? 'System' }}</td>
                <td><strong>Generated At:</strong> {{ now()->format('d M Y, H:i') }}</td>
            </tr>
        </table>
    </div>

    <table class="request-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Employee</th>
                <th>Request Date</th>
                <th>Period</th>
                <th>Reason</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($time_off_requests as $index => $request)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $request->employee->full_name ?? '-' }}</td>
                    <td>{{ \Carbon\Carbon::parse($request->request_date)->format('d M Y') }}</td>
                    <td>
                        {{ \Carbon\Carbon::parse($request->start_date)->format('j F Y') }} - 
                        {{ \Carbon\Carbon::parse($request->end_date)->format('j F Y') }}
                    </td>
                    <td>{{ $request->reason }}</td>
                    <td>{{ ucfirst($request->status) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center;">No time off requests available.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <p>Total Requests: {{ $summary['total'] }}</p>
        <p>Approved: {{ $summary['approved'] }}</p>
        <p>Rejected: {{ $summary['rejected'] }}</p>
        <p>Pending: {{ $summary['pending'] }}</p>
    </div>

    <div class="footer">
        Printed on {{ now()->format('d-m-Y H:i') }}
    </div>
</body>
</html>
